# Generated by Django 4.2.27 on 2026-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TableRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                ("quantity", models.SmallIntegerField(verbose_name="Количество")),
                ("distance", models.SmallIntegerField(verbose_name="Расстояние")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка таблицы",
                "verbose_name_plural": "Строки таблицы",
            },
        ),
    ]
