# Generated by Django 4.2.27 on 2025-12-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spa", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tablerow",
            options={
                "verbose_name": "Строка таблицы",
                "verbose_name_plural": "Строки таблицы",
            },
        ),
    ]
