FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

# Создаем директорию с правильными правами
RUN mkdir -p /app/staticfiles && \
    chown -R nginx:nginx /app/staticfiles && \
    chmod -R 755 /app/staticfiles

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]